# type: args

train:
  epochs: 200
  batch_size: 32
  lr: 1.0e-3
  itr_per_epoch: 1.0e+8

loss:
  lambda_gan: 0.11  # Weight for the GAN loss
  lambda_js: 0.1   # Weight for the JS divergence loss

diffusion:
  layers: 4 
  channels: 64 
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50  # total number of diffusion steps
  T_trunc: 25  # truncation point (T_trunc) at 25 steps
  schedule: "quad"
  is_linear: False

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "random"
